/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc103;

import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact() {
        
        initComponents();
        
        Icon i = facebook.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(facebook.getWidth(), facebook.getHeight(), Image.SCALE_SMOOTH);
        facebook.setIcon(new ImageIcon(image));
        
        Icon a = instagram.getIcon();
        ImageIcon icon1 = (ImageIcon)a;
        Image image1 = icon1.getImage().getScaledInstance(instagram.getWidth(), instagram.getHeight(), Image.SCALE_SMOOTH);
        instagram.setIcon(new ImageIcon(image1));
        
        Icon s = tiktok.getIcon();
        ImageIcon icon2 = (ImageIcon)s;
        Image image2 = icon2.getImage().getScaledInstance(tiktok.getWidth(), tiktok.getHeight(), Image.SCALE_SMOOTH);
        tiktok.setIcon(new ImageIcon(image2));
        
        Icon d = twitter.getIcon();
        ImageIcon icon3 = (ImageIcon)d;
        Image image3 = icon3.getImage().getScaledInstance(twitter.getWidth(), twitter.getHeight(), Image.SCALE_SMOOTH);
        twitter.setIcon(new ImageIcon(image3));
        
        Icon f = youtube.getIcon();
        ImageIcon icon4 = (ImageIcon)f;
        Image image4 = icon4.getImage().getScaledInstance(youtube.getWidth(), youtube.getHeight(), Image.SCALE_SMOOTH);
        youtube.setIcon(new ImageIcon(image4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        youtube = new javax.swing.JLabel();
        tiktok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/contact.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/round.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/request.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/house.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 70, 70));

        jPanel2.setBackground(new java.awt.Color(249, 251, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 18, 11), 2, true), "CONTACT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 36), new java.awt.Color(26, 18, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 42, 33));
        jLabel6.setText("COMPANY ADDRESSS: Pampanga, Angeles City.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 88, -1, -1));

        jLabel7.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 42, 33));
        jLabel7.setText("HOTLINE: 0965-876-4534");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 122, -1, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(60, 42, 33));
        jLabel8.setText("SOCIAL MEDIA APPS: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 162, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 334, -1, -1));

        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/facebook.png"))); // NOI18N
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
        });
        jPanel2.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 40, 40));

        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/instagram.png"))); // NOI18N
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramMouseClicked(evt);
            }
        });
        jPanel2.add(instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, 40));

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/twitter.png"))); // NOI18N
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });
        jPanel2.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 40, 40));

        youtube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/youtube.png"))); // NOI18N
        youtube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                youtubeMouseClicked(evt);
            }
        });
        jPanel2.add(youtube, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 40, 40));

        tiktok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/tiktok.png"))); // NOI18N
        tiktok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiktokMouseClicked(evt);
            }
        });
        jPanel2.add(tiktok, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 780, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/bacground.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(rootPane,"THIS IS THE CONTACT INTERFACE");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        AboutUs AU=new AboutUs();
                AU.show();
                dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        FrontPage FP=new FrontPage();
        FP.show();
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        // TODO add your handling code here:
        Desktop browser = Desktop.getDesktop();
        try
        {
            browser.browse(new URI("https://www.facebook.com/BSnipe15"));
        }
        catch(IOException err){
        }
        catch(URISyntaxException err){}
    }//GEN-LAST:event_facebookMouseClicked

    private void instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseClicked
        // TODO add your handling code here:
        //IGGGGGGGG
        Desktop browser = Desktop.getDesktop();
        try
        {
            browser.browse(new URI("https://www.instagram.com/pizzulu.pizza/"));
        }
        catch(IOException err){
        }
        catch(URISyntaxException err){}
    }//GEN-LAST:event_instagramMouseClicked

    private void tiktokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiktokMouseClicked
        // TODO add your handling code here:
       Desktop browser = Desktop.getDesktop();
        try
        {
            browser.browse(new URI("https://www.tiktok.com/@mommytonifowlerofficial"));
        }
        catch(IOException err){
        }
        catch(URISyntaxException err){}
    }//GEN-LAST:event_tiktokMouseClicked

    private void youtubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        try
        {
            browser.browse(new URI("https://www.youtube.com/@eimifukadatranslations158"));
        }
        catch(IOException err){
        }
        catch(URISyntaxException err){}

    }//GEN-LAST:event_youtubeMouseClicked

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        // TODO add your handling code here:
         // TWITTERRRRRRRRRRRRRRRRRRRRRRRRRR
        Desktop browser = Desktop.getDesktop();
        try
        {
            browser.browse(new URI("https://twitter.com/lemon03172003"));
        }
        catch(IOException err){
        }
        catch(URISyntaxException err){}
    }//GEN-LAST:event_twitterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel facebook;
    private javax.swing.JLabel instagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tiktok;
    private javax.swing.JLabel twitter;
    private javax.swing.JLabel youtube;
    // End of variables declaration//GEN-END:variables
}
