/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc103;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
        initComponents();
        
        Icon i = contact.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(contact.getWidth(), contact.getHeight(), Image.SCALE_SMOOTH);
        contact.setIcon(new ImageIcon(image));
        
        Icon a = request.getIcon();
        ImageIcon icon1 = (ImageIcon)a;
        Image image1 = icon1.getImage().getScaledInstance(request.getWidth(), request.getHeight(), Image.SCALE_SMOOTH);
        request.setIcon(new ImageIcon(image1));
        
        Icon s = pizzaBtn.getIcon();
        ImageIcon icon2 = (ImageIcon)s;
        Image image2 = icon2.getImage().getScaledInstance(pizzaBtn.getWidth(), pizzaBtn.getHeight(), Image.SCALE_SMOOTH);
        pizzaBtn.setIcon(new ImageIcon(image2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contact = new javax.swing.JLabel();
        request = new javax.swing.JLabel();
        pizzaBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/contact.png"))); // NOI18N
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 30, 30));

        request.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/request.png"))); // NOI18N
        request.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestMouseClicked(evt);
            }
        });
        getContentPane().add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 30, 30));

        pizzaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/pizza (3).png"))); // NOI18N
        pizzaBtn.setText("jLabel2");
        pizzaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaBtnMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc103/HOME#2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        // TODO add your handling code here:
        
        Contact con=new Contact();
                con.show();
                dispose();
    }//GEN-LAST:event_contactMouseClicked

    private void requestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseClicked
        // TODO add your handling code here:
        AboutUs AU=new AboutUs();
                AU.show();
                dispose();
    }//GEN-LAST:event_requestMouseClicked

    private void pizzaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaBtnMouseClicked
        // TODO add your handling code here:
        
        Front ap=new Front();
                ap.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_pizzaBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pizzaBtn;
    private javax.swing.JLabel request;
    // End of variables declaration//GEN-END:variables
}
